### ISSUE TITLE
Upgrade to mongodb ~3.x lib

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/core#112]
We're currently on the 2.x series and 3.x has breaking changes, so it'll take a little bit of work.

**Comment by etsuo** [comment]
v3 was just released, so still waiting on types: 

* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22626
* https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22538

Note that it looks like `MongoClient.connect` has changed it behavior:

* http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#.connect
* http://mongodb.github.io/node-mongodb-native/2.0/api/MongoClient.html#.connect

This will break SakuraApi's implementation - see [`src/core/sakura-mongo-db-connection.ts:connect`](https://github.com/sakuraapi/api/blob/develop/src/core/sakura-mongo-db-connection.ts#L52). 

This will express itself as a break in [`getCollection`](https://github.com/sakuraapi/api/blob/develop/src/core/%40model/model.ts#L762) `@Model` injected method.

**Comment by stevenschobert** [comment]
👋 Here!

**Comment by etsuo** [comment]
Thanks for the contribution @stevenschobert!
