### ISSUE TITLE
Update package dependencies

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/core#135]
`sapi outdated`

**Comment by candleshine** [comment]
Hey, I'll work on this.

**Comment by candleshine** [comment]
There is an issue with `@types/colors@latest` and `typescript@2.7`.  It is being tracked at this issue on github.  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9844

This is the reason typescript, is not upgraded.  

`typedoc` is also not upgraded for the same reason.  It forces typescript 2.7.1 to be used.
