### ISSUE TITLE
SakuraApi.close should close DB connections

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/core#152]
See: https://github.com/sakuraapi/core/blob/05ae2f4e5947223169d8a72f9ff2f7dda700edf9/src/core/sakura-api.ts#L392

`.list` opens DB connections, `.close` should properly shut them down.

This is labeled a breaking change in case someone is expecting the DB to still be open after calling close.

**Comment by stevenschobert** [comment]
👋 Gimme!
