### ISSUE TITLE
double registering a service throws error 

### ISSUE THREAD

**Issue by UmamaheshMaxwell** [sakuraapi/core#158]
When we try to register a service twice, sakura throws error saying service already registered. 

```typescript
const providers = [
  SampleService,
  TestService,
  Another Service
];

sapi = testSapi({
  models: [
    user,
    contact,
    about
  ],
  providers: [
    ...providers,
    {for: SomeService, use: MockSomeService},
    {for: SampleService, use: MockSampleService}
  ],
  routables: [
    SomeApi
  ]
});
```
 **Observations**
providers(which is Map) inside registerProviders() method overrides SampleService with its MockSampleService and when we call deregisterDependencies() it would reset all the services except for SampleService because it is not aware of it.

**Expected behaviour**
It should not throw service already registered error and should successfully register the service twice

**Comment by etsuo** [comment]
See #172
