### ISSUE TITLE
Model.toJson mishandles projection if context is provided 

### ISSUE THREAD

**Issue by gowthamrodda** [sakuraapi/core#241]
for example: 
// User model
```
User: {
@Json('myContext')
name: string,
email: string
}

User.toJson({
context: 'myContext',
projection: {
  name: 1
 }
})

output:
{}
```

expected Output:
`{ name: 'somevalue'}`

When a property is decorated with toJson() and pass in context, it mishandles projection.

**Comment by etsuo** [comment]
Hmm. I wrote a unit test for this and it's fine. Turns out we forgot to initialize the properties, so naturally the results are going to be undefined which results in `{}`. @gowthamrodda Thanks for taking the time to open this ticket. It's a good thing to get the extra unit test in regardless.

**Comment by etsuo** [comment]
I found a bug that's not exactly what's reported here, but fits the title of the issue.

If you provide a projection, sapi will project that field even if the context doesn't match. This should not be. Integrators should be required to decorate a property with an `@Json` with a context of `*` if they intend for that to be projected to a DTO in any context.
