### ISSUE TITLE
Allow `@Route` to take method array or method `*`

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/core#90]
It's sometimes desireable to have a single `@Route` handle multiple HTTP methods for a single route.

Currently:
```
@Routable()
export class SomeApi {
  @Route({
    method: 'get',
    path: '/'
  })
  someGetHandler(req, res, next) {
    // handler bound to GET / route
  }
}
```

Proposed Method Array option:
```
@Routable()
export class SomeApi {
  @Route({
    method: ['get', 'post', 'put']
  })
  someHandler(req, res, next) {
    // route bound to GET, POST, or PUT / route
  }
}
```

Proposed Method Array option:
```
@Routable()
export class SomeApi {
  @Route({
    method: '*'
  })
  someHandler(req, res, next) {
    // route bound to all methods for / route
  }
}
```
- [x] rename `core/@routable/HttpMethod` to `ApiMethod` to make it possible to properly define an `HttpMethod` enum for `@Route`. `ApiMethod` actually defines build in handler behavior, not HTTP speced methods
- [x] update `@Route` method to literal types (e.g. 'get' | 'post') or `HttpMethod` enum
- [x] implement method array option
- [x] create a custom type for valid methods (might as well do this while tickling related code -- currently, the `method?` option is of type `string`.
- [x] implement * method option

See:
* https://github.com/sakuraapi/core/blob/develop/src/core/%40routable/route.ts#L47
* https://github.com/sakuraapi/core/blob/develop/src/core/%40routable/route.ts#L113

While implementing this ticket, it might also be a good time to implement:

**Comment by CarsonF** [comment]
Maybe it would make sense to have `@Route` take a list of methods?

**Comment by etsuo** [comment]
@CarsonF that's right; that's what's meant by "method array". Currently, the method option only takes a single value: https://github.com/sakuraapi/core/blob/develop/src/core/%40routable/route.ts#L47.

I'll add some examples to the initial comment above to make it more clear.
